adds configurable dbt cloud host
data-mie/dbt-cloud-cli pull request #39
Opened 2022-01-31 21:26 UTC by ernestoongaro

## Description & motivation
This is to satisfy https://github.com/data-mie/dbt-cloud-cli/issues/38

## Checklist
- [ ] I have written unit tests for new features (e.g., a new command test case in [conftest.py](../tests/conftest.py))
- [ ] I have written integration tests for new features (e.g., a new step in the [CI workflow](workflows/ci.yml))
- [x] I have added descriptions to new commands and arguments
- [ ] I have updated the README.md (if applicable)

2022-01-31 21:33 UTC, ernestoongaro commented
@stumelius I'm going to need a lot of help with the unit and integration tests. Unfortunately for testing urls other than cloud.getdbt.com I don't have a great answer for how we will test them, but effectively the idea is that the functionality is the same, just a different URL.

2022-02-01 11:16 UTC, stumelius requested changes

2022-02-01 11:19 UTC, stumelius commented
Thanks for the PR @ernestoongaro ❤️ I left you a small request for change in the review. There's no need to write new unit or integration tests for this since I have no single tenant instance to test against. As soon as the existing tests pass this PR is good for merging :)

2022-02-01 11:19 UTC, stumelius commented on dbt_cloud/field.py
> +    default_factory=lambda: 'cloud.getdbt.com',
Can you also document the `DBT_CLOUD_HOST` env var in README? :)

2022-02-02 21:31 UTC, ernestoongaro commented on dbt_cloud/field.py
> +    default_factory=lambda: 'cloud.getdbt.com',
Great! I have added to the readme and set the default as you suggested- great idea!

2022-02-02 21:34 UTC, ernestoongaro commented
@stumelius Regarding `black` - I'm getting:

```(dbt_cloud_api_dev) ernesto@Ernesto-Ongaro dbt-cloud-cli % black --check .
All done! ✨ 🍰 ✨
25 files would be left unchanged.```

I don't think that the CI has run again with my changes though?

2022-02-03 05:03 UTC, merged

2022-02-03 05:03 UTC, stumelius commented
Looks good! The integration testing job is failing because it requires secrets from this repo which are not available for forks. I manually verified that the multi-tenant commands are still working 👍